### ISSUE TITLE
About the course at pluralsight

### ISSUE THREAD

**Issue by ozbillwang** [xaviershay/card_game#3]
Sorry to raise ticket here directly, I feel it is hard to do that in pluralsight. I will recommend to upload the videos to Udemy, which you get more viewers.

I am current learning rspec with your course "Testing Ruby Applications with RSpect", and really thanks for giving me the chance to catch it up with this course.

But I have some issues with it.

When run with the code in some videos, I can't make it run properly. So could you please provide the codes for each video, currently I download the code zip file, it has codes only for each module, not each video.

Second, when I learn at "Gatting Started" --> "Deep Dive: Examples and example Groups", I run the command "bin/play", it is fail with below error:

```
$ bin/play
Could not find bank account, you cannot play
```

I understand I need create a new folder `/tmp/bank-accounts`, but what file and the file format I need provide?

**Comment by xaviershay** [comment]
Hello! Sorry for the issues you're running into with the course. Please feel free to email me directly (hello at xaviershay dot com) if you don't want to have to open issues on random projects :)

> I will recommend to upload the videos to Udemy, which you get more viewers.

Thanks for the recommendation, but this was developed as a Pluralsight exclusive.

> So could you please provide the codes for each video, currently I download the code zip file, it has codes only for each module, not each video.

I don't have these available unfortunately. If there's one section in particular you're interested in I can try to recreate it for you.

> I understand I need create a new folder `/tmp/bank-accounts`, but what file and the file format I need provide?

No file format, just `mkdir /tmp/bank-accounts`. I'm guessing this is in an earlier module? I'm looking at the final version of the code and it does this for you.
